- hosts: kube_masters[0]
  gather_facts: false
  tasks:
      - name: Download kube config file
        fetch:
            src: /home/ubuntu/.kube/config
            dest: /tmp/special/
            flat: yes

- hosts: bastion_servers
  gather_facts: false
  tasks:
      - name: create .kube directory
        become: yes
        become_user: ubuntu
        file:
            path: $HOME/.kube
            state: directory
            mode: 0755

      - name: copy kube config file
        copy:
            src: /tmp/special/config
            dest: /home/ubuntu/.kube/config
            owner: ubuntu

      - name: Add Kubernetes apt-key
        become: yes
        apt_key:
            url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
            state: present

      - name: Add Kubernetes APT repository
        become: yes
        apt_repository:
            repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
            state: present
            filename: "kubernetes"

      - name: Install kubectl
        become: yes
        apt:
            name: kubectl
            state: present
            force: yes

      - name: Remove taints on master to schedule pods
        shell: kubectl taint nodes --all node-role.kubernetes.io/master-
        ignore_errors: true

- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
      - name: Delete kube config from local
        file:
            path: /tmp/special
            state: absent
