- hosts: "{{ groups['kube_masters'][0] }}"
  become: yes
  gather_facts: false
  tasks:
      - name: Get join command
        shell: kubeadm token create --print-join-command
        register: join_command_raw

      - name: set join command
        set_fact:
            join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: kube_workers
  become: yes
  tasks:
      - name: Join cluster
        shell: "{{ hostvars[groups['kube_masters'][0]].join_command }} >> node_joined.txt"
        args:
            chdir: $HOME
            creates: node_joined.txt
